### ISSUE TITLE
TODO list for a first version

### ISSUE THREAD

**Issue by nlepage** [nlepage/codyglot#1]
- [ ] Deployment on k8s
- [ ] Clean up tmp dir
- [ ] Improve REPL error management (both HTTP network errors and JSON errors coming from the back)
- [ ] REPL: Add loader while running
- [ ] Add information in REPL (compilation time, running time)
- [ ] Add limitations (inputs size, execution time)
- [ ] Documentation
